USE ranking_system_fussball;
/*DROP TABLE if EXISTS TEAMS;*/
/*
CREATE TABLE TEAMS (
	ID INT(16) AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	STADT VARCHAR(30) NOT NULL,
	GRUEDUNGSJAHR YEAR(4) NOT NULL
	);
	*/
CREATE TABLE USER (
	idUser INT (16) AUTO_INCREMENT PRIMARY KEY,
	USERNAME VARCHAR(50) NOT NULL,
	PASSWORT VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(60) NOT NULL,
	ANLAGEDATUM DATE NOT NULL
	);